package org.codehaus.jremoting.tools.generator;

//import org.codehaus.jremoting.api.MethodNameHelper;
//import org.codehaus.jremoting.server.PublicationDescriptionItem;
//import org.objectweb.asm.*;

public class AsmStubGenerator { // extends AbstractStubGenerator implements Opcodes {

//    public void generateClass(ClassLoader classLoader) {
//
//        // The lookupable service class source.
//        makeClass(classLoader, "Main", getInterfacesToExpose());
//
//        if (getAdditionalFacades() != null) {
//            for (int i = 0; i < getAdditionalFacades().length; i++) {
//                PublicationDescriptionItem facade = getAdditionalFacades()[i];
//                makeClass(classLoader, MethodNameHelper.encodeClassName(facade.getFacadeClass()), new PublicationDescriptionItem[]{facade});
//            }
//        }
//
//
//    }
//
//    private void makeClass(ClassLoader classLoader, String name, PublicationDescriptionItem[] publicationDescriptionItems) {
//
//        ClassWriter cw = new ClassWriter(0);
//        FieldVisitor fv;
//        MethodVisitor mv;
//        AnnotationVisitor av0;
//
//        String[] implementz = getImplements(publicationDescriptionItems);
//
//        cw.visit(V1_1, ACC_PUBLIC + ACC_FINAL + ACC_SUPER, "JRemotingGenerated" + getGenName() + "_" + name , null, "java/lang/Object", implementz);
//
//        cw.visitSource("JRemotingGenerated" + getGenName() + "_" + name + ".java", null);
//
//        {
//            fv = cw.visitField(ACC_PRIVATE + ACC_TRANSIENT, "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;", null, null);
//            fv.visitEnd();
//        }
//
//    }
//
//    private String[] getImplements(PublicationDescriptionItem[] publicationDescriptionItems) {
//        String[] retval =  new String[publicationDescriptionItems.length+1];
//        for (int i = 0; i < publicationDescriptionItems.length; i++) {
//            PublicationDescriptionItem item = publicationDescriptionItems[i];
//            retval[i] = item.getFacadeClass().getName().replace('.','/');
//
//        }
//        retval[retval.length] = "org/codehaus/jremoting/client/Proxy";
//        return retval;
//    }


    public static byte[] dump() throws Exception {

//
//
//

//        {
//            fv = cw.visitField(ACC_STATIC, "class$org$codehaus$jremoting$test$CustomSerializableParam", "Ljava/lang/Class;", null, null);
//            fv.visitEnd();
//        }
//        {
//            fv = cw.visitField(ACC_STATIC, "class$java$lang$String", "Ljava/lang/Class;", null, null);
//            fv.visitEnd();
//        }
//        {
//            fv = cw.visitField(ACC_STATIC, "array$B", "Ljava/lang/Class;", null, null);
//            fv.visitEnd();
//        }
//        {
//            fv = cw.visitField(ACC_STATIC, "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;", null, null);
//            fv.visitEnd();
//        }
//        {
//            fv = cw.visitField(ACC_STATIC, "class$org$codehaus$jremoting$test$TestCallBackListener", "Ljava/lang/Class;", null, null);
//            fv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "<init>", "(Lorg/codehaus/jremoting/client/StubHelper;)V", null, null);
//            mv.visitCode();
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V");
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitFieldInsn(PUTFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitInsn(RETURN);
//            mv.visitMaxs(2, 2);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "codehausRemotingGetReferenceID", "(Ljava/lang/Object;)Ljava/lang/Long;", null, null);
//            mv.visitCode();
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "getReference", "(Ljava/lang/Object;)Ljava/lang/Long;");
//            mv.visitInsn(ARETURN);
//            mv.visitMaxs(2, 2);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_STATIC, "class$", "(Ljava/lang/String;)Ljava/lang/Class;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/ClassNotFoundException");
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitTypeInsn(NEW, "java/lang/NoClassDefFoundError");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/NoClassDefFoundError", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(3, 2);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "equals", "(Ljava/lang/Object;)Z", null, null);
//            mv.visitCode();
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "isEquals", "(Ljava/lang/Object;Ljava/lang/Object;)Z");
//            mv.visitInsn(IRETURN);
//            mv.visitMaxs(3, 2);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "testSpeed", "()V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("testSpeed()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 3);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "testCustomSerializableParameter", "(Lorg/codehaus/jremoting/test/CustomSerializableParam;)Lorg/codehaus/jremoting/test/CustomSerializableParam;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$CustomSerializableParam", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$CustomSerializableParam", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.CustomSerializableParam");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$CustomSerializableParam", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("testCustomSerializableParameter(org.codehaus.jremoting.test.CustomSerializableParam)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "org/codehaus/jremoting/test/CustomSerializableParam");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 5);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "hello", "(Ljava/lang/String;)V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("java.lang.String");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("hello(java.lang.String)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "hello2", "(I)I", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Integer");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(ILOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Integer", "<init>", "(I)V");
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("hello2(int)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Integer");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Integer", "intValue", "()I");
//            mv.visitInsn(IRETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 5);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "bytes", "(B[B)B", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_2);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitInsn(ICONST_2);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Byte");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(ILOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Byte", "<init>", "(B)V");
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_1);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitInsn(ICONST_1);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "array$B", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "array$B", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("[B");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "array$B", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("bytes(byte, [B)");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 5);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Byte");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Byte", "byteValue", "()B");
//            mv.visitInsn(IRETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 5);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 6);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "throwSpecialException", "(I)V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Integer");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(ILOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Integer", "<init>", "(I)V");
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("throwSpecialException(int)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "hello3", "(S)Z", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Short");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(ILOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Short", "<init>", "(S)V");
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("hello3(short)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z");
//            mv.visitInsn(IRETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/beans/PropertyVetoException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/beans/PropertyVetoException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/io/IOException");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/io/IOException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 5);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "hello4", "(FD)Ljava/lang/StringBuffer;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_2);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 5);
//            mv.visitInsn(ICONST_2);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 6);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Float");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(FLOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Float", "<init>", "(F)V");
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(NEW, "java/lang/Double");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(DLOAD, 2);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Double", "<init>", "(D)V");
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("hello4(float, double)");
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitVarInsn(ALOAD, 6);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 7);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/StringBuffer");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 7);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 7);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 8);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "makeTestInterface2", "(Ljava/lang/String;)Lorg/codehaus/jremoting/test/TestInterface2;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("java.lang.String");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFNULL, l4);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l5 = new Label();
//            mv.visitJumpInsn(GOTO, l5);
//            mv.visitLabel(l4);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.TestInterface2");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            mv.visitLabel(l5);
//            mv.visitLdcInsn("makeTestInterface2(java.lang.String)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitLdcInsn("org$codehaus$jremoting$test$TestInterface2");
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequestGettingFacade", "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;");
//            mv.visitTypeInsn(CHECKCAST, "org/codehaus/jremoting/test/TestInterface2");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l6 = new Label();
//            mv.visitJumpInsn(IFEQ, l6);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l6);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l7 = new Label();
//            mv.visitJumpInsn(IFEQ, l7);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l7);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(7, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "morphName", "(Lorg/codehaus/jremoting/test/TestInterface2;)V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.TestInterface2");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("morphName(org.codehaus.jremoting.test.TestInterface2)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "findTestInterface2ByName", "(Ljava/lang/String;)Lorg/codehaus/jremoting/test/TestInterface2;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("java.lang.String");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$java$lang$String", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFNULL, l4);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l5 = new Label();
//            mv.visitJumpInsn(GOTO, l5);
//            mv.visitLabel(l4);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.TestInterface2");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            mv.visitLabel(l5);
//            mv.visitLdcInsn("findTestInterface2ByName(java.lang.String)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitLdcInsn("org$codehaus$jremoting$test$TestInterface2");
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequestGettingFacade", "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;");
//            mv.visitTypeInsn(CHECKCAST, "org/codehaus/jremoting/test/TestInterface2");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l6 = new Label();
//            mv.visitJumpInsn(IFEQ, l6);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l6);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l7 = new Label();
//            mv.visitJumpInsn(IFEQ, l7);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l7);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(7, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "getTestInterface2s", "()[Lorg/codehaus/jremoting/test/TestInterface2;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.TestInterface2");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestInterface2", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitLdcInsn("getTestInterface2s()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitLdcInsn("org$codehaus$jremoting$test$TestInterface2");
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequestGettingFacade", "(Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;");
//            mv.visitTypeInsn(CHECKCAST, "[Lorg/codehaus/jremoting/test/TestInterface2;");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 3);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "getTestObjects", "()[Lorg/codehaus/jremoting/test/TstObject;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("getTestObjects()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "[Lorg/codehaus/jremoting/test/TstObject;");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "changeTestObjectNames", "()V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("changeTestObjectNames()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 3);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "testLong", "(J)V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(NEW, "java/lang/Long");
//            mv.visitInsn(DUP);
//            mv.visitVarInsn(LLOAD, 1);
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Long", "<init>", "(J)V");
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("testLong(long)");
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 5);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 5);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 6);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "makeNewTestObjectNames", "()V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("makeNewTestObjectNames()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 3);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "addCallBackListener", "(Lorg/codehaus/jremoting/test/TestCallBackListener;)Z", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitInsn(ICONST_1);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitInsn(ICONST_0);
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitInsn(AASTORE);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitInsn(ICONST_0);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestCallBackListener", "Ljava/lang/Class;");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFNULL, l2);
//            mv.visitFieldInsn(GETSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestCallBackListener", "Ljava/lang/Class;");
//            Label l3 = new Label();
//            mv.visitJumpInsn(GOTO, l3);
//            mv.visitLabel(l2);
//            mv.visitLdcInsn("org.codehaus.jremoting.test.TestCallBackListener");
//            mv.visitMethodInsn(INVOKESTATIC, "JRemotingGeneratedHello_Main", "class$", "(Ljava/lang/String;)Ljava/lang/Class;");
//            mv.visitInsn(DUP);
//            mv.visitFieldInsn(PUTSTATIC, "JRemotingGeneratedHello_Main", "class$org$codehaus$jremoting$test$TestCallBackListener", "Ljava/lang/Class;");
//            mv.visitLabel(l3);
//            mv.visitInsn(AASTORE);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("addCallBackListener(org.codehaus.jremoting.test.TestCallBackListener)");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Boolean");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Boolean", "booleanValue", "()Z");
//            mv.visitInsn(IRETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l4 = new Label();
//            mv.visitJumpInsn(IFEQ, l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l4);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l5 = new Label();
//            mv.visitJumpInsn(IFEQ, l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l5);
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 4);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(6, 5);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "ping", "()V", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("ping()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processVoidRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)V");
//            mv.visitInsn(RETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 3);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "toString", "()Ljava/lang/String;", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("toString()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/String");
//            mv.visitInsn(ARETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 4);
//            mv.visitEnd();
//        }
//        {
//            mv = cw.visitMethod(ACC_PUBLIC, "hashCode", "()I", null, null);
//            mv.visitCode();
//            Label l0 = new Label();
//            Label l1 = new Label();
//            mv.visitTryCatchBlock(l0, l1, l1, "java/lang/Throwable");
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Object");
//            mv.visitVarInsn(ASTORE, 1);
//            mv.visitInsn(ICONST_0);
//            mv.visitTypeInsn(ANEWARRAY, "java/lang/Class");
//            mv.visitVarInsn(ASTORE, 2);
//            mv.visitLabel(l0);
//            mv.visitVarInsn(ALOAD, 0);
//            mv.visitFieldInsn(GETFIELD, "JRemotingGeneratedHello_Main", "proxyHelper", "Lorg/codehaus/jremoting/client/StubHelper;");
//            mv.visitLdcInsn("hashCode()");
//            mv.visitVarInsn(ALOAD, 1);
//            mv.visitVarInsn(ALOAD, 2);
//            mv.visitMethodInsn(INVOKEINTERFACE, "org/codehaus/jremoting/client/StubHelper", "processObjectRequest", "(Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Class;)Ljava/lang/Object;");
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Integer");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Integer", "intValue", "()I");
//            mv.visitInsn(IRETURN);
//            mv.visitLabel(l1);
//            mv.visitVarInsn(ASTORE, 3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/RuntimeException");
//            Label l2 = new Label();
//            mv.visitJumpInsn(IFEQ, l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/RuntimeException");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l2);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(INSTANCEOF, "java/lang/Error");
//            Label l3 = new Label();
//            mv.visitJumpInsn(IFEQ, l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitTypeInsn(CHECKCAST, "java/lang/Error");
//            mv.visitInsn(ATHROW);
//            mv.visitLabel(l3);
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "printStackTrace", "()V");
//            mv.visitTypeInsn(NEW, "org/codehaus/jremoting/client/InvocationException");
//            mv.visitInsn(DUP);
//            mv.visitTypeInsn(NEW, "java/lang/StringBuffer");
//            mv.visitInsn(DUP);
//            mv.visitLdcInsn("Should never get here: ");
//            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuffer", "<init>", "(Ljava/lang/String;)V");
//            mv.visitVarInsn(ALOAD, 3);
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Throwable", "getMessage", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "append", "(Ljava/lang/String;)Ljava/lang/StringBuffer;");
//            mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuffer", "toString", "()Ljava/lang/String;");
//            mv.visitMethodInsn(INVOKESPECIAL, "org/codehaus/jremoting/client/InvocationException", "<init>", "(Ljava/lang/String;)V");
//            mv.visitInsn(ATHROW);
//            mv.visitMaxs(5, 4);
//            mv.visitEnd();
//        }
//        cw.visitEnd();
//
//        return cw.toByteArray();

      return null;
    }

}
